version: 2
executorType: docker
containerInfo:
  - image: rh389/node-base
  - image: deangiberson/aws-dynamodb-local

jobs:
  build:
    workDir: ~/workspace
    steps:
      - type: checkout
      - restore_cache:
          key: v1-pnpm
      - type: shell
        shell: /bin/sh
        command: corepack enable && pnpm install --frozen-lockfile && pnpm test
      - save_cache:
          key: v1-pnpm-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/workspace/node_modules

workflows:
  version: 2
  build:
    jobs:
      - build

